language: python
python:
  - "3.6"
cache: pip
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database movies;' -U postgres
install:
  - pip install -r requirements.txt

script:
  - pytest --cov=.

after_failure:
  - coveralls
after_success:
  - coveralls
