
version: '2'

services:
  database:
    restart: always
    image: postgres
    env_file:
      - prod.env
    ports:
      - "5433:5432"
    expose:
      - '5432'
  web:
    build: .
    command: bash startup.sh
    volumes:
      - .:/tickets
    ports:
      - "5000:5000"
    env_file:
      - prod.env
    depends_on:
      - database