version: "2.1"

services:
  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=cinema
    ports:
      - "5433:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "cinema", "-U", "postgres" ]
      timeout: 20s
      retries: 10
  web:
    build: .
    volumes:
      - .:/tickets
    ports:
      - "5000:5000"
    env_file:
      - prod.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_pass@database:5432/cinema
      - DEBUG=False
      - FLASK_APP=run.py
    depends_on:
      database:
        condition: service_healthy
    command: bash startup.sh
    
